wandb:
  project: 'wrime-bert'
  mode: 'online'
data:
  train_path: './data/train.tsv'
  test_path: './data/test.tsv'
label:
  target: 'gap'
  sentiment: 'anger'
  num_classes: 2
model:
  pretrained_model: 'cl-tohoku/bert-base-japanese-whole-word-masking'
  dropout_prob: 0.1
train:
  batch_size: 32
  learning_rate: 2e-5
  num_epochs: 3
